---
# Default variables for base_system role

base_system_packages:
  - vim-enhanced
  - btop
  - curl
  - ncdu
  - tree
  - gnupg2
  - python3-pip
  - make
  - git
  - bash-completion
  - zsh
  - fzf
  - lsd
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - flameshot
  - terminator
  - plocate
  - dnf-plugins-core
  - tmux
  - ghostty
  - cargo
  - ansible-lint
