---
# Default variables for kubernetes role

kubernetes_version: "1.30"
kubernetes_repo_base: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/rpm"
kubernetes_freelens_rpm_url: ""  # Set via extra vars if needed
